import type { Metadata } from "next";
import "./globals.css";

import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable"

import Sidebar from "@/components/cq/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        
        <ResizablePanelGroup direction="horizontal" className="min-h-screen">
          <Sidebar></Sidebar>
          <ResizableHandle withHandle/>
          <ResizablePanel defaultSize={80} minSize={50}>
            <div className="ml-4 mt-4">
              {children}
            </div>
          </ResizablePanel>
        </ResizablePanelGroup>
      </body>
    </html>
  );
}
